/**
 * Recipe → canonical ingredient links (public surface).
 *
 * Generated by scripts/nutrition/resolve-dishes.mjs. This module adds the
 * lookup the therapeutics bridge + nutrition composition read through.
 */

import type { RecipeIngredientLink } from "@/types/ingredient";
import { RECIPE_LINKS } from "./recipe-links.generated";

export { RECIPE_LINKS };

export function getRecipeLink(slug: string): RecipeIngredientLink | null {
  return RECIPE_LINKS[slug] ?? null;
}
