/**
 * GENERATED by scripts/nutrition/resolve-dishes.mjs — DO NOT EDIT BY HAND.
 *
 * Each guided-cook dish's ingredient lines resolved to canonical ids + grams.
 * Unresolved lines are omitted (grow the registry to cover them); servings
 * default to 4 until per-dish serving data exists.
 */

import type { RecipeIngredientLink } from "@/types/ingredient";

export const RECIPE_LINKS: Record<string, RecipeIngredientLink> = {
  "caesar-salad": {
    recipeSlug: "caesar-salad",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "garlic", grams: 6, isOptional: false },
      { ingredientId: "olive-oil", grams: 40.5, isOptional: false },
    ],
  },
  "garlic-bread": {
    recipeSlug: "garlic-bread",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "garlic", grams: 9, isOptional: false }],
  },
  tabbouleh: {
    recipeSlug: "tabbouleh",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "tomato", grams: 492, isOptional: false },
      { ingredientId: "onion", grams: 440, isOptional: false },
      { ingredientId: "olive-oil", grams: 47.25, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  "tomato-soup": {
    recipeSlug: "tomato-soup",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "tomato", grams: 246, isOptional: false },
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "garlic", grams: 9, isOptional: false },
      { ingredientId: "chicken-breast", grams: 0, isOptional: false },
    ],
  },
  guacamole: {
    recipeSlug: "guacamole",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 0, isOptional: false },
      { ingredientId: "tomato", grams: 123, isOptional: true },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  bruschetta: {
    recipeSlug: "bruschetta",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "tomato", grams: 453.59, isOptional: false },
      { ingredientId: "garlic", grams: 9, isOptional: false },
      { ingredientId: "olive-oil", grams: 67.5, isOptional: false },
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
    ],
  },
  gyoza: {
    recipeSlug: "gyoza",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 0, isOptional: false },
      { ingredientId: "garlic", grams: 3, isOptional: false },
      { ingredientId: "white-rice", grams: 11.56, isOptional: false },
    ],
  },
  elote: {
    recipeSlug: "elote",
    servingsPerRecipe: 4,
    lines: [],
  },
  "miso-soup": {
    recipeSlug: "miso-soup",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "onion", grams: 0, isOptional: true }],
  },
  "spring-rolls": {
    recipeSlug: "spring-rolls",
    servingsPerRecipe: 4,
    lines: [],
  },
  "caprese-salad": {
    recipeSlug: "caprese-salad",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "tomato", grams: 0, isOptional: false },
      { ingredientId: "olive-oil", grams: 33.75, isOptional: false },
      { ingredientId: "garlic", grams: 3, isOptional: false },
    ],
  },
  "baingan-bharta": {
    recipeSlug: "baingan-bharta",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "tomato", grams: 369, isOptional: false },
      { ingredientId: "garlic", grams: 27, isOptional: false },
    ],
  },
  karaage: {
    recipeSlug: "karaage",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "chicken-breast", grams: 680.39, isOptional: false },
      { ingredientId: "garlic", grams: 3, isOptional: false },
    ],
  },
  edamame: {
    recipeSlug: "edamame",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "table-salt", grams: 6.08, isOptional: false }],
  },
  "pico-de-gallo": {
    recipeSlug: "pico-de-gallo",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "tomato", grams: 738, isOptional: false },
      { ingredientId: "onion", grams: 55, isOptional: false },
      { ingredientId: "table-salt", grams: 4.56, isOptional: false },
    ],
  },
  onigiri: {
    recipeSlug: "onigiri",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 370, isOptional: false },
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
    ],
  },
  minestrone: {
    recipeSlug: "minestrone",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "olive-oil", grams: 40.5, isOptional: false },
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "garlic", grams: 12, isOptional: false },
      { ingredientId: "tomato", grams: 123, isOptional: false },
      { ingredientId: "spinach", grams: 60, isOptional: false },
    ],
  },
  esquites: {
    recipeSlug: "esquites",
    servingsPerRecipe: 4,
    lines: [],
  },
  "mexican-rice": {
    recipeSlug: "mexican-rice",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 277.5, isOptional: false },
      { ingredientId: "onion", grams: 55, isOptional: false },
      { ingredientId: "garlic", grams: 6, isOptional: false },
      { ingredientId: "tomato", grams: 180, isOptional: false },
      { ingredientId: "chicken-breast", grams: 0, isOptional: false },
      { ingredientId: "table-salt", grams: 4.56, isOptional: false },
    ],
  },
  arancini: {
    recipeSlug: "arancini",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 277.5, isOptional: false },
      { ingredientId: "chicken-breast", grams: 0, isOptional: false },
      { ingredientId: "egg", grams: 0, isOptional: false },
    ],
  },
  tzatziki: {
    recipeSlug: "tzatziki",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "greek-yogurt", grams: 367.5, isOptional: false },
      { ingredientId: "garlic", grams: 0, isOptional: false },
      { ingredientId: "olive-oil", grams: 27, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "aloo-gobi": {
    recipeSlug: "aloo-gobi",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "garlic", grams: 4.25, isOptional: false },
      { ingredientId: "tomato", grams: 246, isOptional: false },
    ],
  },
  "lachha-paratha": {
    recipeSlug: "lachha-paratha",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "table-salt", grams: 3.04, isOptional: false }],
  },
  "baba-ganoush": {
    recipeSlug: "baba-ganoush",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "garlic", grams: 4.5, isOptional: false },
      { ingredientId: "table-salt", grams: 4.56, isOptional: false },
      { ingredientId: "olive-oil", grams: 33.75, isOptional: false },
    ],
  },
  roti: {
    recipeSlug: "roti",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "table-salt", grams: 3.04, isOptional: false }],
  },
  tempura: {
    recipeSlug: "tempura",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "broccoli", grams: 182, isOptional: false },
      { ingredientId: "egg", grams: 50, isOptional: false },
    ],
  },
  "refried-beans": {
    recipeSlug: "refried-beans",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 55, isOptional: false },
      { ingredientId: "garlic", grams: 6, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  "basmati-rice": {
    recipeSlug: "basmati-rice",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 185, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "sweet-potato-fries": {
    recipeSlug: "sweet-potato-fries",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "olive-oil", grams: 27, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  "seaweed-salad": {
    recipeSlug: "seaweed-salad",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "white-rice", grams: 23.13, isOptional: false }],
  },
  churros: {
    recipeSlug: "churros",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "egg", grams: 50, isOptional: false }],
  },
  "potato-salad": {
    recipeSlug: "potato-salad",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 40, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  "onion-rings": {
    recipeSlug: "onion-rings",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 220, isOptional: false },
      { ingredientId: "garlic", grams: 2.83, isOptional: false },
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
    ],
  },
  "french-fries": {
    recipeSlug: "french-fries",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "table-salt", grams: 0, isOptional: false }],
  },
  "corn-on-cob": {
    recipeSlug: "corn-on-cob",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "table-salt", grams: 0, isOptional: false }],
  },
  fattoush: {
    recipeSlug: "fattoush",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "tomato", grams: 180, isOptional: false },
      { ingredientId: "olive-oil", grams: 54, isOptional: false },
    ],
  },
  "stuffed-grape-leaves": {
    recipeSlug: "stuffed-grape-leaves",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 185, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
      { ingredientId: "olive-oil", grams: 54, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  takoyaki: {
    recipeSlug: "takoyaki",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "egg", grams: 100, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
    ],
  },
  congee: {
    recipeSlug: "congee",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 138.75, isOptional: false },
      { ingredientId: "chicken-breast", grams: 0, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
    ],
  },
  "mixed-green-salad": {
    recipeSlug: "mixed-green-salad",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "olive-oil", grams: 67.5, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  japchae: {
    recipeSlug: "japchae",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "spinach", grams: 85.05, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
    ],
  },
  tteokbokki: {
    recipeSlug: "tteokbokki",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 0, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
    ],
  },
  satay: {
    recipeSlug: "satay",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "chicken-breast", grams: 0, isOptional: false },
      { ingredientId: "garlic", grams: 9, isOptional: false },
    ],
  },
  "sticky-rice": {
    recipeSlug: "sticky-rice",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "white-rice", grams: 370, isOptional: false }],
  },
  larb: {
    recipeSlug: "larb",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "chicken-breast", grams: 0, isOptional: false },
      { ingredientId: "white-rice", grams: 23.13, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
    ],
  },
  "bean-sprout-salad": {
    recipeSlug: "bean-sprout-salad",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "garlic", grams: 6, isOptional: false },
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
    ],
  },
  "naan-bread": {
    recipeSlug: "naan-bread",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
      { ingredientId: "greek-yogurt", grams: 81.67, isOptional: false },
      { ingredientId: "olive-oil", grams: 27, isOptional: false },
    ],
  },
  "baked-potato": {
    recipeSlug: "baked-potato",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "olive-oil", grams: 27, isOptional: false },
      { ingredientId: "table-salt", grams: 18.25, isOptional: false },
    ],
  },
  "roasted-asparagus": {
    recipeSlug: "roasted-asparagus",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "olive-oil", grams: 27, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "summer-rolls": {
    recipeSlug: "summer-rolls",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 0, isOptional: false },
      { ingredientId: "white-rice", grams: 56.7, isOptional: false },
    ],
  },
  "creamed-spinach": {
    recipeSlug: "creamed-spinach",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "spinach", grams: 453.59, isOptional: false },
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "garlic", grams: 9, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  "dal-tadka": {
    recipeSlug: "dal-tadka",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "tomato", grams: 123, isOptional: false },
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "garlic", grams: 12, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  spanakopita: {
    recipeSlug: "spanakopita",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "spinach", grams: 907.18, isOptional: false },
      { ingredientId: "egg", grams: 150, isOptional: false },
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "onion", grams: 440, isOptional: false },
      { ingredientId: "olive-oil", grams: 108, isOptional: false },
    ],
  },
  raita: {
    recipeSlug: "raita",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "greek-yogurt", grams: 490, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  tamagoyaki: {
    recipeSlug: "tamagoyaki",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "egg", grams: 150, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  "mapo-tofu": {
    recipeSlug: "mapo-tofu",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "black-beans", grams: 12.13, isOptional: false },
      { ingredientId: "garlic", grams: 12, isOptional: false },
      { ingredientId: "chicken-breast", grams: 0, isOptional: false },
      { ingredientId: "onion", grams: 330, isOptional: false },
    ],
  },
  "goma-ae-spinach": {
    recipeSlug: "goma-ae-spinach",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "spinach", grams: 0, isOptional: false }],
  },
  "plain-dosa": {
    recipeSlug: "plain-dosa",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 370, isOptional: false },
      { ingredientId: "red-lentils", grams: 96, isOptional: false },
      { ingredientId: "white-rice", grams: 23.13, isOptional: true },
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
    ],
  },
  "mango-chutney": {
    recipeSlug: "mango-chutney",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "garlic", grams: 6, isOptional: false },
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "agedashi-tofu": {
    recipeSlug: "agedashi-tofu",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "onion", grams: 220, isOptional: false }],
  },
  "smashed-cucumber-salad": {
    recipeSlug: "smashed-cucumber-salad",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
      { ingredientId: "garlic", grams: 9, isOptional: false },
      { ingredientId: "white-rice", grams: 23.13, isOptional: false },
      { ingredientId: "garlic", grams: 12.75, isOptional: false },
    ],
  },
  "bok-choy-garlic": {
    recipeSlug: "bok-choy-garlic",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "garlic", grams: 13.5, isOptional: false }],
  },
  "sigeumchi-namul": {
    recipeSlug: "sigeumchi-namul",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "spinach", grams: 226.8, isOptional: false },
      { ingredientId: "garlic", grams: 6, isOptional: false },
      { ingredientId: "onion", grams: 220, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "soba-noodles": {
    recipeSlug: "soba-noodles",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 23.13, isOptional: false },
      { ingredientId: "garlic", grams: 3, isOptional: false },
      { ingredientId: "onion", grams: 330, isOptional: false },
    ],
  },
  "tortilla-chips": {
    recipeSlug: "tortilla-chips",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "olive-oil", grams: 27, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  samosa: {
    recipeSlug: "samosa",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "table-salt", grams: 6.08, isOptional: false }],
  },
  pickles: {
    recipeSlug: "pickles",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "table-salt", grams: 18.25, isOptional: false },
      { ingredientId: "garlic", grams: 9, isOptional: false },
    ],
  },
  "papaya-salad": {
    recipeSlug: "papaya-salad",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "tomato", grams: 984, isOptional: false },
      { ingredientId: "garlic", grams: 6, isOptional: false },
    ],
  },
  "bao-buns": {
    recipeSlug: "bao-buns",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "table-salt", grams: 1.52, isOptional: false }],
  },
  "crispy-wontons": {
    recipeSlug: "crispy-wontons",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "garlic", grams: 6, isOptional: false },
      { ingredientId: "onion", grams: 330, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  "wild-rice": {
    recipeSlug: "wild-rice",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 185, isOptional: false },
      { ingredientId: "chicken-breast", grams: 0, isOptional: false },
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
    ],
  },
  "korean-pancake": {
    recipeSlug: "korean-pancake",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "egg", grams: 50, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "white-rice", grams: 23.13, isOptional: false },
    ],
  },
  "coconut-soup": {
    recipeSlug: "coconut-soup",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "chicken-breast", grams: 0, isOptional: false },
      { ingredientId: "chicken-breast", grams: 226.8, isOptional: false },
    ],
  },
  "pita-chips": {
    recipeSlug: "pita-chips",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "olive-oil", grams: 40.5, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
      { ingredientId: "garlic", grams: 0.71, isOptional: true },
    ],
  },
  papadum: {
    recipeSlug: "papadum",
    servingsPerRecipe: 4,
    lines: [],
  },
  "egg-drop-soup-with-veggies": {
    recipeSlug: "egg-drop-soup-with-veggies",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "chicken-breast", grams: 0, isOptional: false },
      { ingredientId: "egg", grams: 150, isOptional: false },
      { ingredientId: "onion", grams: 330, isOptional: false },
    ],
  },
  "dan-dan-noodles": {
    recipeSlug: "dan-dan-noodles",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "garlic", grams: 9, isOptional: false },
      { ingredientId: "spinach", grams: 113.4, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
    ],
  },
  "hot-and-sour-soup": {
    recipeSlug: "hot-and-sour-soup",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "chicken-breast", grams: 0, isOptional: false },
      { ingredientId: "egg", grams: 100, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
    ],
  },
  upma: {
    recipeSlug: "upma",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "chickpeas", grams: 12.5, isOptional: false },
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
    ],
  },
  "curd-rice": {
    recipeSlug: "curd-rice",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 370, isOptional: false },
      { ingredientId: "greek-yogurt", grams: 367.5, isOptional: false },
      { ingredientId: "red-lentils", grams: 4, isOptional: false },
      { ingredientId: "table-salt", grams: 4.56, isOptional: false },
    ],
  },
  "cauliflower-rice": {
    recipeSlug: "cauliflower-rice",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "garlic", grams: 6, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "air-fryer-broccoli": {
    recipeSlug: "air-fryer-broccoli",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "broccoli", grams: 364, isOptional: false },
      { ingredientId: "olive-oil", grams: 27, isOptional: false },
      { ingredientId: "garlic", grams: 1.42, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "batata-bhaji": {
    recipeSlug: "batata-bhaji",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
    ],
  },
  "brown-rice-bowl": {
    recipeSlug: "brown-rice-bowl",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "brown-rice", grams: 190, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "roasted-carrots-and-pearl-onions": {
    recipeSlug: "roasted-carrots-and-pearl-onions",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 160, isOptional: false },
      { ingredientId: "olive-oil", grams: 40.5, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "air-fryer-sweet-potato-fries": {
    recipeSlug: "air-fryer-sweet-potato-fries",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "olive-oil", grams: 13.5, isOptional: false },
      { ingredientId: "garlic", grams: 1.42, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "chinese-broccoli": {
    recipeSlug: "chinese-broccoli",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "broccoli", grams: 0, isOptional: false },
      { ingredientId: "garlic", grams: 6, isOptional: false },
    ],
  },
  mandu: {
    recipeSlug: "mandu",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "garlic", grams: 9, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
    ],
  },
  "banh-mi": {
    recipeSlug: "banh-mi",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 34.69, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "onion-raita": {
    recipeSlug: "onion-raita",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "greek-yogurt", grams: 245, isOptional: false },
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: true },
    ],
  },
  "coconut-chutney": {
    recipeSlug: "coconut-chutney",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "chickpeas", grams: 25, isOptional: false },
      { ingredientId: "table-salt", grams: 4.56, isOptional: false },
    ],
  },
  "tamarind-date-chutney": {
    recipeSlug: "tamarind-date-chutney",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  kachumber: {
    recipeSlug: "kachumber",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "tomato", grams: 246, isOptional: false },
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  phulka: {
    recipeSlug: "phulka",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "table-salt", grams: 3.04, isOptional: false }],
  },
  "medu-vada": {
    recipeSlug: "medu-vada",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "table-salt", grams: 6.08, isOptional: false }],
  },
  uttapam: {
    recipeSlug: "uttapam",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "tomato", grams: 123, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  "masala-papad": {
    recipeSlug: "masala-papad",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "tomato", grams: 123, isOptional: false },
    ],
  },
  hiyayakko: {
    recipeSlug: "hiyayakko",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "onion", grams: 220, isOptional: false }],
  },
  sunomono: {
    recipeSlug: "sunomono",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
      { ingredientId: "white-rice", grams: 34.69, isOptional: false },
    ],
  },
  "nasu-dengaku": {
    recipeSlug: "nasu-dengaku",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "onion", grams: 0, isOptional: true }],
  },
  kongnamul: {
    recipeSlug: "kongnamul",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "garlic", grams: 6, isOptional: false },
      { ingredientId: "onion", grams: 220, isOptional: false },
      { ingredientId: "table-salt", grams: 0, isOptional: false },
    ],
  },
  "bhindi-fry-side": {
    recipeSlug: "bhindi-fry-side",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "garlic", grams: 9, isOptional: false },
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
    ],
  },
  "baingan-bharta-side": {
    recipeSlug: "baingan-bharta-side",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "garlic", grams: 12, isOptional: false },
      { ingredientId: "tomato", grams: 246, isOptional: false },
      { ingredientId: "table-salt", grams: 9.13, isOptional: false },
    ],
  },
  "cabbage-thoran": {
    recipeSlug: "cabbage-thoran",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
    ],
  },
  "palak-corn": {
    recipeSlug: "palak-corn",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "spinach", grams: 0, isOptional: false },
      { ingredientId: "onion", grams: 110, isOptional: false },
      { ingredientId: "garlic", grams: 9, isOptional: false },
      { ingredientId: "tomato", grams: 123, isOptional: false },
      { ingredientId: "table-salt", grams: 6.08, isOptional: false },
    ],
  },
  "air-fryer-brussels-sprouts": {
    recipeSlug: "air-fryer-brussels-sprouts",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "olive-oil", grams: 27, isOptional: false },
      { ingredientId: "garlic", grams: 1.42, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "air-fryer-green-beans": {
    recipeSlug: "air-fryer-green-beans",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "olive-oil", grams: 13.5, isOptional: false },
      { ingredientId: "garlic", grams: 1.42, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  "gamja-jorim": {
    recipeSlug: "gamja-jorim",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "garlic", grams: 9, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: true },
    ],
  },
  "goi-cuon": {
    recipeSlug: "goi-cuon",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 0, isOptional: false },
      { ingredientId: "white-rice", grams: 0, isOptional: false },
    ],
  },
  "lotus-root-salad": {
    recipeSlug: "lotus-root-salad",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 34.69, isOptional: false },
      { ingredientId: "garlic", grams: 3, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
    ],
  },
  "som-tum": {
    recipeSlug: "som-tum",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "garlic", grams: 6, isOptional: false },
      { ingredientId: "tomato", grams: 0, isOptional: false },
    ],
  },
  "nam-tok": {
    recipeSlug: "nam-tok",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "white-rice", grams: 17.34, isOptional: false },
      { ingredientId: "onion", grams: 0, isOptional: false },
    ],
  },
  "pak-boong": {
    recipeSlug: "pak-boong",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "spinach", grams: 0, isOptional: false },
      { ingredientId: "garlic", grams: 13.5, isOptional: false },
    ],
  },
  "gai-yang": {
    recipeSlug: "gai-yang",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "chicken-breast", grams: 907.18, isOptional: false },
      { ingredientId: "garlic", grams: 18, isOptional: false },
    ],
  },
  "yum-woon-sen": {
    recipeSlug: "yum-woon-sen",
    servingsPerRecipe: 4,
    lines: [],
  },
  hummus: {
    recipeSlug: "hummus",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "chickpeas", grams: 0, isOptional: false },
      { ingredientId: "garlic", grams: 4.5, isOptional: false },
      { ingredientId: "olive-oil", grams: 27, isOptional: false },
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
    ],
  },
  kimchi: {
    recipeSlug: "kimchi",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "table-salt", grams: 73, isOptional: false },
      { ingredientId: "garlic", grams: 18, isOptional: false },
      { ingredientId: "onion", grams: 440, isOptional: false },
    ],
  },
  coleslaw: {
    recipeSlug: "coleslaw",
    servingsPerRecipe: 4,
    lines: [{ ingredientId: "table-salt", grams: 0, isOptional: false }],
  },
  cornbread: {
    recipeSlug: "cornbread",
    servingsPerRecipe: 4,
    lines: [
      { ingredientId: "table-salt", grams: 3.04, isOptional: false },
      { ingredientId: "egg", grams: 100, isOptional: false },
    ],
  },
};
