/**
 * Ingredient ingest spec — the data the USDA ingest reads (the "system within
 * the system"): adding an ingredient is adding one row here, then re-running
 * scripts/nutrition/usda-ingest.mjs. Nutrient vectors come from USDA by fdcId;
 * the hand-authored fields are claim-neutral food identity + mass conversions.
 *
 * Fields: id, fdcId (SR Legacy), name, group (FoodGroup), classes
 * (TherapeuticClass[]), cup (g per US cup | null), piece (g per piece | null),
 * aliases (lowercased match keys; keep them specific to avoid mis-resolution).
 *
 * Water IS included now (it was excluded as "zero nutrition") — once ingredient
 * coverage became a surfaced honesty signal, leaving the single most common
 * line (water) unresolved penalised every recipe that lists it. Resolving water
 * carries ~0 nutrition but makes the "from N of M ingredients" note accurate.
 */

export const SPEC = [
  // ── legumes ──────────────────────────────────────────────────────────────
  {
    id: "red-lentils",
    fdcId: 172420,
    name: "Red lentils",
    group: "legume",
    classes: ["soluble-fiber", "plant-protein"],
    cup: 192,
    piece: null,
    aliases: [
      "masoor dal",
      "masoor",
      "red lentil",
      "lentil",
      "lentils",
      "dal",
      "daal",
      "toor dal",
      "split lentils",
    ],
  },
  {
    id: "chickpeas",
    fdcId: 173756,
    name: "Chickpeas",
    group: "legume",
    classes: ["soluble-fiber", "plant-protein"],
    cup: 200,
    piece: null,
    aliases: [
      "chickpea",
      "garbanzo",
      "garbanzo beans",
      "chana",
      "kabuli chana",
    ],
  },
  {
    id: "black-beans",
    fdcId: 173734,
    name: "Black beans",
    group: "legume",
    classes: ["soluble-fiber", "plant-protein"],
    cup: 194,
    piece: null,
    aliases: ["black bean"],
  },
  {
    id: "tofu",
    fdcId: 172448,
    name: "Tofu",
    group: "legume",
    classes: ["plant-protein"],
    cup: 252,
    piece: null,
    aliases: ["firm tofu", "bean curd", "silken tofu", "extra firm tofu"],
  },
  // ── grains ───────────────────────────────────────────────────────────────
  {
    id: "oats",
    fdcId: 169705,
    name: "Oats",
    group: "grain",
    classes: ["beta-glucan", "soluble-fiber", "whole-grain"],
    cup: 81,
    piece: null,
    aliases: ["oat", "oatmeal", "rolled oats", "porridge oats"],
  },
  {
    id: "barley",
    fdcId: 170283,
    name: "Barley",
    group: "grain",
    classes: ["beta-glucan", "whole-grain", "soluble-fiber"],
    cup: 184,
    piece: null,
    aliases: ["pearl barley", "hulled barley", "pearled barley"],
  },
  {
    id: "brown-rice",
    fdcId: 169703,
    name: "Brown rice",
    group: "grain",
    classes: ["whole-grain"],
    cup: 190,
    piece: null,
    aliases: ["wholegrain rice"],
  },
  {
    id: "white-rice",
    fdcId: 169756,
    name: "White rice",
    group: "grain",
    classes: ["refined-grain"],
    cup: 185,
    piece: null,
    aliases: [
      "rice",
      "basmati rice",
      "jasmine rice",
      "long grain rice",
      "white rice",
      "cooked rice",
      "steamed rice",
    ],
  },
  {
    id: "rice-noodles",
    fdcId: 169742,
    name: "Rice noodles",
    group: "grain",
    classes: ["refined-grain"],
    cup: null,
    piece: null,
    aliases: [
      "rice noodle",
      "flat rice noodles",
      "vermicelli",
      "rice vermicelli",
    ],
  },
  {
    id: "all-purpose-flour",
    fdcId: 168894,
    name: "All-purpose flour",
    group: "grain",
    classes: ["refined-grain"],
    cup: 125,
    piece: null,
    aliases: ["all purpose flour", "plain flour", "flour", "maida"],
  },
  {
    id: "cornstarch",
    fdcId: 169698,
    name: "Cornstarch",
    group: "grain",
    classes: ["refined-grain"],
    cup: 128,
    piece: null,
    aliases: ["corn starch", "cornflour", "corn flour"],
  },
  {
    id: "bread",
    fdcId: 174924,
    name: "White bread",
    group: "grain",
    classes: ["refined-grain"],
    cup: null,
    piece: 25,
    aliases: [
      "white bread",
      "bread for croutons",
      "bread slices",
      "sliced bread",
      "toast",
    ],
  },
  // ── nuts / seeds ─────────────────────────────────────────────────────────
  {
    id: "almonds",
    fdcId: 170567,
    name: "Almonds",
    group: "nut-seed",
    classes: ["nuts"],
    cup: 143,
    piece: null,
    aliases: ["almond"],
  },
  {
    id: "walnuts",
    fdcId: 170187,
    name: "Walnuts",
    group: "nut-seed",
    classes: ["nuts", "omega-3-source"],
    cup: 100,
    piece: null,
    aliases: ["walnut"],
  },
  {
    id: "roasted-peanuts",
    fdcId: 173806,
    name: "Peanuts",
    group: "nut-seed",
    classes: ["nuts"],
    cup: 146,
    piece: null,
    aliases: ["roasted peanuts", "peanuts", "peanut", "dry roasted peanuts"],
  },
  {
    id: "peanut-butter",
    fdcId: 172430,
    name: "Peanut butter",
    group: "nut-seed",
    classes: ["nuts"],
    cup: 258,
    piece: null,
    aliases: ["peanut butter"],
  },
  {
    id: "sesame-seeds",
    fdcId: 170150,
    name: "Sesame seeds",
    group: "nut-seed",
    classes: [],
    cup: 144,
    piece: null,
    aliases: ["toasted sesame seeds", "white sesame seeds", "sesame seed"],
  },
  {
    id: "tahini",
    fdcId: 168604,
    name: "Tahini",
    group: "nut-seed",
    classes: [],
    cup: 240,
    piece: null,
    aliases: ["sesame paste"],
  },
  {
    id: "coconut",
    fdcId: 168585,
    name: "Coconut",
    group: "nut-seed",
    classes: ["saturated-fat-rich"],
    cup: 80,
    piece: null,
    aliases: ["desiccated coconut", "shredded coconut", "dried coconut"],
  },
  // ── seafood / proteins ───────────────────────────────────────────────────
  {
    id: "salmon",
    fdcId: 173686,
    name: "Salmon",
    group: "seafood",
    classes: ["oily-fish", "omega-3-source"],
    cup: null,
    piece: 140,
    aliases: ["atlantic salmon", "wild salmon", "salmon fillet"],
  },
  {
    id: "sardines",
    fdcId: 175139,
    name: "Sardines",
    group: "seafood",
    classes: ["oily-fish", "omega-3-source"],
    cup: null,
    piece: 24,
    aliases: ["sardine"],
  },
  {
    id: "shrimp",
    fdcId: 175179,
    name: "Shrimp",
    group: "seafood",
    classes: [],
    cup: null,
    piece: 6,
    aliases: ["prawns", "prawn", "shrimps"],
  },
  {
    id: "chicken-breast",
    fdcId: 171077,
    name: "Chicken breast",
    group: "poultry",
    classes: [],
    cup: null,
    piece: 170,
    aliases: ["chicken", "chicken breasts", "chicken thigh", "chicken thighs"],
  },
  {
    id: "ground-pork",
    fdcId: 168372,
    name: "Ground pork",
    group: "red-meat",
    classes: ["saturated-fat-rich"],
    cup: null,
    piece: null,
    aliases: ["pork mince", "minced pork", "pork"],
  },
  {
    id: "ground-beef",
    fdcId: 174036,
    name: "Ground beef",
    group: "red-meat",
    classes: ["saturated-fat-rich"],
    cup: null,
    piece: null,
    aliases: ["beef mince", "minced beef", "beef"],
  },
  {
    id: "egg",
    fdcId: 171287,
    name: "Egg",
    group: "egg",
    classes: [],
    cup: null,
    piece: 50,
    aliases: ["eggs", "whole egg"],
  },
  // ── leafy greens / cruciferous ───────────────────────────────────────────
  {
    id: "kale",
    fdcId: 168421,
    name: "Kale",
    group: "leafy-green",
    classes: ["cruciferous"],
    cup: 67,
    piece: null,
    aliases: [],
  },
  {
    id: "spinach",
    fdcId: 168462,
    name: "Spinach",
    group: "leafy-green",
    classes: [],
    cup: 30,
    piece: null,
    aliases: ["baby spinach"],
  },
  {
    id: "romaine",
    fdcId: 169247,
    name: "Romaine lettuce",
    group: "leafy-green",
    classes: [],
    cup: 47,
    piece: null,
    aliases: ["romaine", "lettuce", "cos lettuce"],
  },
  {
    id: "broccoli",
    fdcId: 170379,
    name: "Broccoli",
    group: "vegetable",
    classes: ["cruciferous"],
    cup: 91,
    piece: null,
    aliases: [],
  },
  {
    id: "napa-cabbage",
    fdcId: 169979,
    name: "Napa cabbage",
    group: "vegetable",
    classes: ["cruciferous"],
    cup: 76,
    piece: null,
    aliases: ["chinese cabbage", "wombok"],
  },
  {
    id: "green-cabbage",
    fdcId: 169975,
    name: "Cabbage",
    group: "vegetable",
    classes: ["cruciferous"],
    cup: 89,
    piece: null,
    aliases: ["green cabbage"],
  },
  // ── vegetables / aromatics ───────────────────────────────────────────────
  {
    id: "garlic",
    fdcId: 169230,
    name: "Garlic",
    group: "vegetable",
    classes: [],
    cup: 136,
    piece: 3,
    aliases: ["garlic clove", "garlic cloves", "minced garlic"],
  },
  {
    id: "onion",
    fdcId: 170000,
    name: "Onion",
    group: "vegetable",
    classes: [],
    cup: 160,
    piece: 110,
    aliases: ["onions", "yellow onion", "red onion", "white onion"],
  },
  {
    id: "scallion",
    fdcId: 170005,
    name: "Scallion",
    group: "vegetable",
    classes: [],
    cup: 100,
    piece: 15,
    aliases: [
      "scallions",
      "spring onion",
      "spring onions",
      "green onion",
      "green onions",
    ],
  },
  {
    id: "shallots",
    fdcId: 170499,
    name: "Shallots",
    group: "vegetable",
    classes: [],
    cup: 160,
    piece: 25,
    aliases: ["shallot"],
  },
  {
    id: "tomato",
    fdcId: 170457,
    name: "Tomato",
    group: "vegetable",
    classes: [],
    cup: 180,
    piece: 123,
    aliases: ["tomatoes", "roma tomato", "cherry tomatoes"],
  },
  {
    id: "tomato-paste",
    fdcId: 170459,
    name: "Tomato paste",
    group: "vegetable",
    classes: [],
    cup: 262,
    piece: null,
    aliases: ["tomato puree", "tomato concentrate"],
  },
  {
    id: "carrot",
    fdcId: 170393,
    name: "Carrot",
    group: "vegetable",
    classes: [],
    cup: 128,
    piece: 61,
    aliases: ["carrots"],
  },
  {
    id: "celery",
    fdcId: 169988,
    name: "Celery",
    group: "vegetable",
    classes: [],
    cup: 101,
    piece: 40,
    aliases: ["celery stalk", "celery stalks"],
  },
  {
    id: "cucumber",
    fdcId: 168409,
    name: "Cucumber",
    group: "vegetable",
    classes: [],
    cup: 119,
    piece: 300,
    aliases: ["cucumbers"],
  },
  {
    id: "jalapeno",
    fdcId: 168576,
    name: "Jalapeño",
    group: "vegetable",
    classes: [],
    cup: 90,
    piece: 14,
    aliases: [
      "jalapeno",
      "green chili",
      "green chilli",
      "green chilies",
      "serrano",
      "green chili slit",
      "thai chili",
      "bird's eye chili",
    ],
  },
  {
    id: "bell-pepper",
    fdcId: 170108,
    name: "Bell pepper",
    group: "vegetable",
    classes: [],
    cup: 149,
    piece: 119,
    aliases: ["red bell pepper", "capsicum", "red pepper", "green bell pepper"],
  },
  {
    id: "potato",
    fdcId: 170026,
    name: "Potato",
    group: "vegetable",
    classes: [],
    cup: 150,
    piece: 173,
    aliases: ["potatoes"],
  },
  {
    id: "eggplant",
    fdcId: 169228,
    name: "Eggplant",
    group: "vegetable",
    classes: [],
    cup: 82,
    piece: 458,
    aliases: ["aubergine", "brinjal"],
  },
  {
    id: "green-beans",
    fdcId: 169961,
    name: "Green beans",
    group: "vegetable",
    classes: [],
    cup: 100,
    piece: null,
    aliases: ["snap beans", "string beans"],
  },
  {
    id: "mushroom",
    fdcId: 169251,
    name: "Mushroom",
    group: "vegetable",
    classes: [],
    cup: 70,
    piece: 18,
    aliases: ["mushrooms", "white mushrooms", "button mushrooms", "cremini"],
  },
  {
    id: "shiitake",
    fdcId: 169242,
    name: "Shiitake mushrooms",
    group: "vegetable",
    classes: [],
    cup: 145,
    piece: null,
    aliases: ["shiitake"],
  },
  {
    id: "corn",
    fdcId: 169998,
    name: "Corn",
    group: "vegetable",
    classes: [],
    cup: 154,
    piece: null,
    aliases: ["corn kernels", "sweetcorn", "sweet corn"],
  },
  // ── herbs / spices ───────────────────────────────────────────────────────
  {
    id: "cilantro",
    fdcId: 169997,
    name: "Cilantro",
    group: "herb-spice",
    classes: [],
    cup: 16,
    piece: null,
    aliases: [
      "fresh cilantro",
      "fresh coriander",
      "coriander leaves",
      "cilantro leaves",
      "fresh cilantro chopped",
    ],
  },
  {
    id: "parsley",
    fdcId: 170416,
    name: "Parsley",
    group: "herb-spice",
    classes: [],
    cup: 60,
    piece: null,
    aliases: ["fresh parsley", "flat leaf parsley"],
  },
  {
    id: "basil",
    fdcId: 172232,
    name: "Basil",
    group: "herb-spice",
    classes: [],
    cup: 24,
    piece: null,
    aliases: ["fresh basil", "thai basil", "basil leaves"],
  },
  {
    id: "mint",
    fdcId: 173474,
    name: "Mint",
    group: "herb-spice",
    classes: [],
    cup: 30,
    piece: null,
    aliases: ["fresh mint", "fresh mint leaves", "mint leaves"],
  },
  {
    id: "dill",
    fdcId: 172233,
    name: "Dill",
    group: "herb-spice",
    classes: [],
    cup: 9,
    piece: null,
    aliases: ["fresh dill", "dill weed"],
  },
  {
    id: "ginger",
    fdcId: 169231,
    name: "Ginger",
    group: "herb-spice",
    classes: [],
    cup: 96,
    piece: 15,
    aliases: [
      "fresh ginger",
      "ginger root",
      "ginger grated",
      "ginger minced",
      "ginger paste",
    ],
  },
  {
    id: "turmeric",
    fdcId: 172231,
    name: "Turmeric",
    group: "herb-spice",
    classes: [],
    cup: 120,
    piece: null,
    aliases: ["turmeric powder", "ground turmeric", "haldi"],
  },
  {
    id: "black-pepper",
    fdcId: 170931,
    name: "Black pepper",
    group: "herb-spice",
    classes: [],
    cup: 115,
    piece: null,
    aliases: [
      "pepper",
      "ground black pepper",
      "peppercorns",
      "black peppercorns",
    ],
  },
  {
    id: "cumin",
    fdcId: 170923,
    name: "Cumin",
    group: "herb-spice",
    classes: [],
    cup: 100,
    piece: null,
    aliases: ["cumin seeds", "cumin powder", "ground cumin", "jeera"],
  },
  {
    id: "coriander-seed",
    fdcId: 170922,
    name: "Coriander seed",
    group: "herb-spice",
    classes: [],
    cup: 90,
    piece: null,
    aliases: [
      "coriander powder",
      "coriander seeds",
      "ground coriander",
      "dhania",
    ],
  },
  {
    id: "mustard-seeds",
    fdcId: 170929,
    name: "Mustard seeds",
    group: "herb-spice",
    classes: [],
    cup: 90,
    piece: null,
    aliases: ["mustard seed", "brown mustard seeds", "black mustard seeds"],
  },
  {
    id: "paprika",
    fdcId: 171329,
    name: "Paprika",
    group: "herb-spice",
    classes: [],
    cup: 108,
    piece: null,
    aliases: ["smoked paprika"],
  },
  {
    id: "cayenne",
    fdcId: 170932,
    name: "Chili powder",
    group: "herb-spice",
    classes: [],
    cup: 90,
    piece: null,
    aliases: [
      "gochugaru",
      "korean red pepper flakes",
      "korean chili flakes",
      "cayenne",
      "red chili powder",
      "chili powder",
      "red pepper flakes",
      "dried chili flakes",
      "chili flakes",
      "dried red chili",
      "dried chili",
    ],
  },
  // ── fats / oils ──────────────────────────────────────────────────────────
  {
    id: "olive-oil",
    fdcId: 171413,
    name: "Olive oil",
    group: "fat-oil",
    classes: ["olive-oil"],
    cup: 216,
    piece: null,
    aliases: ["extra virgin olive oil", "evoo"],
  },
  {
    id: "vegetable-oil",
    fdcId: 172336,
    name: "Vegetable oil",
    group: "fat-oil",
    classes: [],
    cup: 218,
    piece: null,
    aliases: [
      "neutral oil",
      "canola oil",
      "cooking oil",
      "oil",
      "neutral oil for frying",
      "frying oil",
      "sunflower oil",
    ],
  },
  {
    id: "sesame-oil",
    fdcId: 171016,
    name: "Sesame oil",
    group: "fat-oil",
    classes: [],
    cup: 218,
    piece: null,
    aliases: ["toasted sesame oil"],
  },
  {
    id: "coconut-oil",
    fdcId: 171412,
    name: "Coconut oil",
    group: "fat-oil",
    classes: ["saturated-fat-rich"],
    cup: 218,
    piece: null,
    aliases: [],
  },
  {
    id: "butter",
    fdcId: 173410,
    name: "Butter",
    group: "dairy",
    classes: ["saturated-fat-rich"],
    cup: 227,
    piece: null,
    aliases: [
      "salted butter",
      "unsalted butter",
      "butter melted",
      "melted butter",
    ],
  },
  {
    id: "ghee",
    fdcId: 173412,
    name: "Ghee",
    group: "fat-oil",
    classes: ["saturated-fat-rich"],
    cup: 205,
    piece: null,
    aliases: ["clarified butter"],
  },
  // ── dairy ────────────────────────────────────────────────────────────────
  {
    id: "greek-yogurt",
    fdcId: 170894,
    name: "Greek yogurt",
    group: "dairy",
    classes: ["fermented"],
    cup: 245,
    piece: null,
    aliases: ["yogurt", "yoghurt", "plain yogurt"],
  },
  {
    id: "milk",
    fdcId: 171265,
    name: "Milk",
    group: "dairy",
    classes: [],
    cup: 244,
    piece: null,
    aliases: ["whole milk", "dairy milk"],
  },
  {
    id: "heavy-cream",
    fdcId: 170859,
    name: "Heavy cream",
    group: "dairy",
    classes: ["saturated-fat-rich"],
    cup: 238,
    piece: null,
    aliases: ["heavy whipping cream", "double cream", "cream"],
  },
  {
    id: "parmesan",
    fdcId: 171247,
    name: "Parmesan",
    group: "dairy",
    classes: [],
    cup: 100,
    piece: null,
    aliases: ["parmesan cheese", "parmigiano", "parmesan grated"],
  },
  {
    id: "coconut-milk",
    fdcId: 170173,
    name: "Coconut milk",
    group: "other",
    classes: ["saturated-fat-rich"],
    cup: 226,
    piece: null,
    aliases: [],
  },
  // ── condiments / sauces / sweeteners ─────────────────────────────────────
  {
    id: "soy-sauce",
    fdcId: 174277,
    name: "Soy sauce",
    group: "condiment",
    classes: ["high-sodium"],
    cup: 255,
    piece: null,
    aliases: ["light soy sauce", "dark soy sauce", "tamari", "shoyu"],
  },
  {
    id: "fish-sauce",
    fdcId: 174531,
    name: "Fish sauce",
    group: "condiment",
    classes: ["high-sodium"],
    cup: 270,
    piece: null,
    aliases: ["nam pla"],
  },
  {
    id: "table-salt",
    fdcId: 173468,
    name: "Salt",
    group: "condiment",
    classes: ["high-sodium"],
    cup: 292,
    piece: null,
    aliases: ["salt", "sea salt", "kosher salt"],
  },
  {
    id: "mayonnaise",
    fdcId: 171009,
    name: "Mayonnaise",
    group: "condiment",
    classes: [],
    cup: 220,
    piece: null,
    aliases: ["mayo", "kewpie mayo", "japanese mayonnaise"],
  },
  {
    id: "dijon-mustard",
    fdcId: 172234,
    name: "Dijon mustard",
    group: "condiment",
    classes: [],
    cup: 249,
    piece: null,
    aliases: [
      "mustard",
      "prepared mustard",
      "wholegrain mustard",
      "yellow mustard",
    ],
  },
  {
    id: "apple-cider-vinegar",
    fdcId: 173469,
    name: "Vinegar",
    group: "condiment",
    classes: [],
    cup: 239,
    piece: null,
    aliases: [
      "apple cider vinegar",
      "cider vinegar",
      "rice vinegar",
      "white vinegar",
      "rice wine vinegar",
    ],
  },
  {
    id: "mirin",
    fdcId: 169070,
    name: "Mirin",
    group: "condiment",
    classes: ["added-sugar"],
    cup: 240,
    piece: null,
    aliases: [],
  },
  {
    id: "sake",
    fdcId: 174837,
    name: "Sake",
    group: "beverage",
    classes: [],
    cup: 235,
    piece: null,
    aliases: ["rice wine"],
  },
  {
    id: "sugar",
    fdcId: 169655,
    name: "Sugar",
    group: "sweetener",
    classes: ["added-sugar"],
    cup: 200,
    piece: null,
    aliases: [
      "granulated sugar",
      "white sugar",
      "caster sugar",
      "superfine sugar",
    ],
  },
  {
    id: "brown-sugar",
    fdcId: 168833,
    name: "Brown sugar",
    group: "sweetener",
    classes: ["added-sugar"],
    cup: 220,
    piece: null,
    aliases: ["palm sugar", "jaggery", "coconut sugar"],
  },
  {
    id: "honey",
    fdcId: 169640,
    name: "Honey",
    group: "sweetener",
    classes: ["added-sugar"],
    cup: 339,
    piece: null,
    aliases: [],
  },
  // ── fruit ────────────────────────────────────────────────────────────────
  {
    id: "lemon",
    fdcId: 167746,
    name: "Lemon",
    group: "fruit",
    classes: [],
    cup: null,
    piece: 58,
    aliases: ["lemons"],
  },
  {
    id: "lime",
    fdcId: 168155,
    name: "Lime",
    group: "fruit",
    classes: [],
    cup: null,
    piece: 67,
    aliases: ["limes"],
  },
  {
    id: "lemon-juice",
    fdcId: 167747,
    name: "Lemon juice",
    group: "fruit",
    classes: [],
    cup: 244,
    piece: null,
    aliases: ["fresh lemon juice"],
  },
  {
    id: "lime-juice",
    fdcId: 168156,
    name: "Lime juice",
    group: "fruit",
    classes: [],
    cup: 246,
    piece: null,
    aliases: ["fresh lime juice"],
  },
  // ── tail (Gap 3) ─────────────────────────────────────────────────────────
  {
    id: "oyster-sauce",
    fdcId: 174529,
    name: "Oyster sauce",
    group: "condiment",
    classes: ["high-sodium"],
    cup: 270,
    piece: null,
    aliases: [],
  },
  {
    id: "hoisin",
    fdcId: 172886,
    name: "Hoisin sauce",
    group: "condiment",
    classes: ["added-sugar"],
    cup: 270,
    piece: null,
    aliases: ["hoisin"],
  },
  {
    id: "balsamic-vinegar",
    fdcId: 172241,
    name: "Balsamic vinegar",
    group: "condiment",
    classes: [],
    cup: 255,
    piece: null,
    aliases: ["balsamic", "balsamic glaze"],
  },
  {
    id: "daikon",
    fdcId: 168451,
    name: "Daikon",
    group: "vegetable",
    classes: [],
    cup: 116,
    piece: 338,
    aliases: ["daikon radish", "white radish", "mooli"],
  },
  {
    id: "avocado",
    fdcId: 171705,
    name: "Avocado",
    group: "fruit",
    classes: [],
    cup: 150,
    piece: 201,
    aliases: ["avocados", "ripe avocado"],
  },
  {
    id: "bulgur",
    fdcId: 170688,
    name: "Bulgur",
    group: "grain",
    classes: ["whole-grain"],
    cup: 140,
    piece: null,
    aliases: ["bulgur wheat", "fine bulgur", "cracked wheat"],
  },
  {
    id: "anchovy",
    fdcId: 174183,
    name: "Anchovy",
    group: "seafood",
    classes: ["oily-fish", "omega-3-source"],
    cup: null,
    piece: 4,
    aliases: ["anchovies", "anchovy paste", "anchovy fillets"],
  },
  {
    id: "wakame",
    fdcId: 170496,
    name: "Wakame",
    group: "vegetable",
    classes: [],
    cup: 80,
    piece: null,
    aliases: [
      "dried wakame",
      "seaweed",
      "dried wakame seaweed",
      "nori",
      "kombu",
    ],
  },
  {
    id: "edamame",
    fdcId: 168411,
    name: "Edamame",
    group: "legume",
    classes: ["plant-protein"],
    cup: 155,
    piece: null,
    aliases: ["soybeans", "soy beans"],
  },
  {
    id: "mango",
    fdcId: 169910,
    name: "Mango",
    group: "fruit",
    classes: [],
    cup: 165,
    piece: 200,
    aliases: ["mangoes"],
  },
  {
    id: "feta",
    fdcId: 173420,
    name: "Feta",
    group: "dairy",
    classes: ["fermented"],
    cup: 150,
    piece: null,
    aliases: ["feta cheese"],
  },
  {
    id: "mozzarella",
    fdcId: 170845,
    name: "Mozzarella",
    group: "dairy",
    classes: [],
    cup: 112,
    piece: null,
    aliases: ["mozzarella cheese", "fresh mozzarella"],
  },
  {
    id: "cauliflower",
    fdcId: 169986,
    name: "Cauliflower",
    group: "vegetable",
    classes: ["cruciferous"],
    cup: 107,
    piece: null,
    aliases: [],
  },
  {
    id: "zucchini",
    fdcId: 169291,
    name: "Zucchini",
    group: "vegetable",
    classes: [],
    cup: 124,
    piece: 196,
    aliases: ["courgette"],
  },
  {
    id: "bean-sprouts",
    fdcId: 169957,
    name: "Bean sprouts",
    group: "vegetable",
    classes: [],
    cup: 104,
    piece: null,
    aliases: ["mung bean sprouts", "beansprouts"],
  },
  {
    id: "sweet-potato",
    fdcId: 168482,
    name: "Sweet potato",
    group: "vegetable",
    classes: [],
    cup: 133,
    piece: 130,
    aliases: ["sweet potatoes", "yam"],
  },
  {
    id: "cod",
    fdcId: 171955,
    name: "Cod",
    group: "seafood",
    classes: [],
    cup: null,
    piece: 180,
    aliases: ["white fish"],
  },
  {
    id: "tilapia",
    fdcId: 175176,
    name: "Tilapia",
    group: "seafood",
    classes: [],
    cup: null,
    piece: 145,
    aliases: [],
  },
  // ── supporting ingredients for the meal exemplars ────────────────────────
  {
    id: "pasta",
    fdcId: 169736,
    name: "Pasta",
    group: "grain",
    classes: ["refined-grain"],
    cup: 91,
    piece: null,
    aliases: ["spaghetti", "penne", "macaroni", "dry pasta", "linguine"],
  },
  {
    id: "egg-noodles",
    fdcId: 169731,
    name: "Egg noodles",
    group: "grain",
    classes: ["refined-grain"],
    cup: 38,
    piece: null,
    aliases: ["udon", "ramen noodles", "wheat noodles", "noodles"],
  },
  {
    id: "tortilla",
    fdcId: 175037,
    name: "Tortilla",
    group: "grain",
    classes: ["refined-grain"],
    cup: null,
    piece: 30,
    aliases: ["tortillas", "flour tortilla", "wrap", "wraps"],
  },
  {
    id: "beef-steak",
    fdcId: 172174,
    name: "Beef steak",
    group: "red-meat",
    classes: ["saturated-fat-rich"],
    cup: null,
    piece: 200,
    aliases: ["steak", "sirloin", "beef sirloin"],
  },
  {
    id: "lamb",
    fdcId: 174370,
    name: "Lamb",
    group: "red-meat",
    classes: ["saturated-fat-rich"],
    cup: null,
    piece: null,
    aliases: ["ground lamb", "lamb mince"],
  },
  {
    id: "paneer",
    fdcId: 170851,
    name: "Paneer",
    group: "dairy",
    classes: [],
    cup: 246,
    piece: null,
    aliases: ["ricotta", "cottage cheese", "fresh cheese"],
  },
  // ── water + leaveners + cheeses (registry-growth: resolve the most common
  //    unresolved lines to raise honest coverage; water carries ~0 nutrition
  //    but IS a real ingredient line, so resolving it makes coverage accurate
  //    rather than penalising every recipe that lists water). ──
  {
    id: "water",
    fdcId: 174158,
    name: "Water",
    group: "beverage",
    classes: [],
    cup: 237,
    piece: null,
    aliases: [
      "water",
      "cold water",
      "hot water",
      "warm water",
      "filtered water",
      "boiling water",
      "ice water",
      "ice",
      "ice cubes",
      "room temperature water",
    ],
  },
  {
    id: "baking-powder",
    fdcId: 172803,
    name: "Baking powder",
    group: "other",
    classes: [],
    cup: 230,
    piece: null,
    aliases: ["baking powder", "double-acting baking powder"],
  },
  {
    id: "baking-soda",
    fdcId: 175040,
    name: "Baking soda",
    group: "other",
    classes: [],
    cup: 220,
    piece: null,
    aliases: ["baking soda", "sodium bicarbonate", "bicarbonate of soda"],
  },
  {
    id: "cotija-cheese",
    fdcId: 170898,
    name: "Cotija cheese",
    group: "dairy",
    classes: [],
    cup: 132,
    piece: null,
    aliases: ["cotija cheese", "cotija", "queso cotija"],
  },
  {
    id: "mascarpone",
    fdcId: 173418,
    name: "Mascarpone",
    group: "dairy",
    classes: [],
    cup: 232,
    piece: null,
    aliases: ["mascarpone", "mascarpone cheese"],
  },
  {
    id: "active-dry-yeast",
    fdcId: 175043,
    name: "Active dry yeast",
    group: "other",
    classes: [],
    cup: 136,
    piece: 7,
    aliases: ["instant yeast", "active dry yeast", "dry yeast", "yeast"],
  },
];
