/**
 * Resolve guided-cook dishes → canonical ingredient links
 * (docs/INGREDIENT-NUTRITION-ARCHITECTURE-PLAN.md, Phase 3).
 *
 * For every dish in guided-cook-steps.ts, resolve each ingredient line to a
 * canonical id (registry) + a mass in grams (quantity normalizer), and emit a
 * vendored, drift-guarded link table. Prints a coverage report so the registry
 * is grown deliberately against real gaps, never guessed.
 *
 *   node scripts/nutrition/resolve-dishes.mjs          # write links + report
 *   node scripts/nutrition/resolve-dishes.mjs --report # report only
 */

import fs from "node:fs";
import path from "node:path";

const base = new URL("../../", import.meta.url);
const guided = await import(new URL("src/data/guided-cook-steps.ts", base));
const meals = await import(new URL("src/data/meal-ingredients.ts", base));
const servingsMod = await import(new URL("src/data/dish-servings.ts", base));
const resolver = await import(
  new URL("src/lib/nutrition/resolve-dish-lines.ts", base)
);

const { guidedCookData } = guided;
const { MEAL_INGREDIENTS } = meals;
const { sideServings } = servingsMod;
const { resolveDishLines } = resolver;

const DEFAULT_SERVINGS = 4;

const slugs = Object.keys(guidedCookData);
const links = {};
const unresolvedNames = new Map();
let totalLines = 0;
let resolvedLines = 0;
let massedLines = 0;

for (const slug of slugs) {
  const dish = guidedCookData[slug];
  // Same pure resolver the drift guard checks against — script just orchestrates.
  const { lines, originalLineCount, unresolved } = resolveDishLines(
    dish.ingredients ?? [],
  );
  totalLines += originalLineCount;
  resolvedLines += lines.length;
  massedLines += lines.filter((l) => l.grams > 0).length;
  for (const name of unresolved) {
    unresolvedNames.set(name, (unresolvedNames.get(name) ?? 0) + 1);
  }
  links[slug] = {
    recipeSlug: slug,
    servingsPerRecipe: sideServings(slug),
    originalLineCount,
    lines,
  };
}

// Meals — quantified exemplar lists (Gap 1), keyed by meal slug + own servings.
const mealSlugs = Object.keys(MEAL_INGREDIENTS);
for (const slug of mealSlugs) {
  const meal = MEAL_INGREDIENTS[slug];
  const { lines, originalLineCount, unresolved } = resolveDishLines(
    meal.ingredients,
  );
  totalLines += originalLineCount;
  resolvedLines += lines.length;
  massedLines += lines.filter((l) => l.grams > 0).length;
  for (const name of unresolved) {
    unresolvedNames.set(name, (unresolvedNames.get(name) ?? 0) + 1);
  }
  links[slug] = {
    recipeSlug: slug,
    servingsPerRecipe: meal.servings,
    originalLineCount,
    lines,
  };
}

// ---- coverage report ----
const pct = (n, d) => (d ? ((100 * n) / d).toFixed(1) : "0.0");
console.log(`\n=== dish resolution coverage ===`);
console.log(`dishes:            ${slugs.length}`);
console.log(`ingredient lines:  ${totalLines}`);
console.log(
  `resolved to id:    ${resolvedLines} (${pct(resolvedLines, totalLines)}%)`,
);
console.log(
  `+ massed to grams: ${massedLines} (${pct(massedLines, totalLines)}%)`,
);
const fullyResolved = slugs.filter(
  (s) =>
    links[s].lines.length > 0 &&
    guidedCookData[s].ingredients.length === links[s].lines.length,
).length;
console.log(`fully-resolved dishes: ${fullyResolved} / ${slugs.length}`);

const top = (m, n) => [...m.entries()].sort((a, b) => b[1] - a[1]).slice(0, n);
console.log(`\n--- top unresolved ingredient names (count) ---`);
for (const [name, c] of top(unresolvedNames, 30)) {
  console.log(`  ${String(c).padStart(3)}  ${name}`);
}

if (process.argv.includes("--report")) process.exit(0);

// ---- emit vendored links (sides + meals) ----
const allSlugs = Object.keys(links);
const body = allSlugs
  .map((slug) => {
    const l = links[slug];
    const lines = l.lines
      .map(
        (x) =>
          `      { ingredientId: "${x.ingredientId}", grams: ${x.grams}, isOptional: ${x.isOptional}${x.fryingMedium ? ", fryingMedium: true" : ""} },`,
      )
      .join("\n");
    return `  "${slug}": {
    recipeSlug: "${slug}",
    servingsPerRecipe: ${l.servingsPerRecipe},
    originalLineCount: ${l.originalLineCount},
    lines: [
${lines}
    ],
  },`;
  })
  .join("\n");

const out = `/**
 * GENERATED by scripts/nutrition/resolve-dishes.mjs — DO NOT EDIT BY HAND.
 *
 * Each guided-cook dish's ingredient lines resolved to canonical ids + grams.
 * Unresolved lines are omitted (grow the registry to cover them); servings
 * default to ${DEFAULT_SERVINGS} until per-dish serving data exists.
 */

import type { RecipeIngredientLink } from "@/types/ingredient";

export const RECIPE_LINKS: Record<string, RecipeIngredientLink> = {
${body}
};
`;

const outPath = path.join(
  process.cwd(),
  "src/data/ingredients/recipe-links.generated.ts",
);
fs.writeFileSync(outPath, out);
console.log(
  `\nwrote ${allSlugs.length} dish links (${slugs.length} sides + ${mealSlugs.length} meals) → ${outPath}`,
);
