/**
 * USDA → canonical ingredient registry ingest
 * (docs/INGREDIENT-NUTRITION-ARCHITECTURE-PLAN.md, Phase 2).
 *
 * Reads a USDA FoodData Central JSON dataset and emits a SMALL, vendored
 * registry of only the ingredients Sous uses — real per-100g nutrient vectors
 * keyed to USDA fdcIds. The multi-hundred-MB source is NEVER committed; only
 * the generated registry is. Re-run after `pnpm` to refresh:
 *
 *   1. Download (public domain):
 *      https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_sr_legacy_food_json_2018-04.json.zip
 *   2. node scripts/nutrition/usda-ingest.mjs <path-to-sr-legacy.json>
 *
 * SR Legacy is the primary source: unlike Foundation Foods (analytically
 * incomplete — e.g. no fiber on "Lentils, dry"), SR Legacy carries complete
 * macro + micronutrient panels with the standard nutrient numbers.
 */

import fs from "node:fs";
import path from "node:path";

// nutrient.number → our NutrientVector key (first present wins).
const NUMBER_TO_KEY = {
  calcium_mg: ["301"],
  iron_mg: ["303"],
  vitaminD_mcg: ["328"],
  vitaminA_mcg_rae: ["320"],
  fiber_g: ["291"],
  potassium_mg: ["306"],
  zinc_mg: ["309"],
  magnesium_mg: ["304"],
  vitaminB12_mcg: ["418"],
  choline_mg: ["421"],
  sodium_mg: ["307"],
  addedSugar_g: ["539"],
  saturatedFat_g: ["606"],
};
// Energy: prefer kcal (208), fall back to Atwater factors.
const ENERGY_NUMBERS = ["208", "958", "957"];
// Omega-3 long+short chain, summed: ALA, EPA, DHA, DPA.
const OMEGA3_NUMBERS = ["851", "629", "621", "631"];

// The ingest spec lives in its own data module — adding an ingredient is adding
// one row there, not editing this pipeline (docs plan: "a system within the system").
import { SPEC } from "./ingredient-spec.mjs";

function amountByNumbers(byNumber, numbers) {
  for (const n of numbers) {
    if (byNumber[n] !== undefined) return byNumber[n];
  }
  return 0;
}

function round(n) {
  return Math.round(n * 1000) / 1000;
}

function buildVector(food) {
  const byNumber = {};
  for (const fn of food.foodNutrients ?? []) {
    const num = fn.nutrient?.number;
    if (num && byNumber[num] === undefined) byNumber[num] = fn.amount ?? 0;
  }
  const v = { calories: round(amountByNumbers(byNumber, ENERGY_NUMBERS)) };
  for (const [key, nums] of Object.entries(NUMBER_TO_KEY)) {
    v[key] = round(amountByNumbers(byNumber, nums));
  }
  v.omega3_g = round(
    OMEGA3_NUMBERS.reduce((sum, n) => sum + (byNumber[n] ?? 0), 0),
  );
  return v;
}

function main() {
  const srcPath = process.argv[2];
  if (!srcPath) {
    console.error("usage: node usda-ingest.mjs <sr-legacy-json-path>");
    process.exit(1);
  }
  const j = JSON.parse(fs.readFileSync(srcPath, "utf8"));
  const foods = (j.SRLegacyFoods ?? j.FoundationFoods ?? []).filter(Boolean);
  const byId = new Map(foods.map((f) => [f.fdcId, f]));

  const entries = [];
  const missing = [];
  for (const s of SPEC) {
    const food = byId.get(s.fdcId);
    if (!food) {
      missing.push(`${s.id} (fdcId ${s.fdcId})`);
      continue;
    }
    const per100g = buildVector(food);
    if (!per100g.calories) {
      console.warn(`WARN ${s.id}: no energy value found`);
    }
    entries.push({ s, per100g, usdaName: food.description });
  }

  if (missing.length) {
    console.error(
      "MISSING fdcIds (not in dataset):\n  " + missing.join("\n  "),
    );
    process.exit(2);
  }

  const KEYS = [
    "calories",
    "calcium_mg",
    "iron_mg",
    "vitaminD_mcg",
    "vitaminA_mcg_rae",
    "fiber_g",
    "potassium_mg",
    "omega3_g",
    "zinc_mg",
    "magnesium_mg",
    "vitaminB12_mcg",
    "choline_mg",
    "sodium_mg",
    "addedSugar_g",
    "saturatedFat_g",
  ];

  const body = entries
    .map(({ s, per100g, usdaName }) => {
      const vec = KEYS.map((k) => `${k}: ${per100g[k]}`).join(", ");
      const aliases = JSON.stringify(s.aliases);
      const classes = JSON.stringify(s.classes);
      return `  "${s.id}": {
    id: "${s.id}",
    name: "${s.name}",
    aliases: ${aliases},
    fdcId: ${s.fdcId},
    fdcDataType: "sr-legacy",
    foodGroup: "${s.group}",
    therapeuticClasses: ${classes},
    // USDA SR Legacy: ${usdaName.replace(/\*\//g, "")}
    per100g: { ${vec} },
    densityGPerCup: ${s.cup},
    gramsPerPiece: ${s.piece},
    provenance: "usda-fdc",
    confidence: "mapped",
  },`;
    })
    .join("\n");

  const out = `/**
 * GENERATED by scripts/nutrition/usda-ingest.mjs — DO NOT EDIT BY HAND.
 *
 * Canonical ingredient registry. Per-100g nutrient vectors are real USDA
 * FoodData Central SR Legacy values (public domain); food-identity facts
 * (group, therapeutic classes, mass conversions) are curated in the ingest
 * spec. ${entries.length} ingredients.
 */

import type { Ingredient } from "@/types/ingredient";

export const INGREDIENTS: Record<string, Ingredient> = {
${body}
};
`;

  const outPath = path.join(
    process.cwd(),
    "src/data/ingredients/registry.generated.ts",
  );
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
  console.log(`wrote ${entries.length} ingredients → ${outPath}`);
}

main();
