/**
 * Codegen: extract a LIGHTWEIGHT per-dish summary (prep/cook minutes +
 * ingredient names) from the 599KB src/data/guided-cook-steps.ts.
 *
 * Today-side clients (quest-card, text-prompt, surprise-me) only need those
 * fields, but importing them from guided-cook-steps drags the full step data
 * (instructions, hacks, cuisine facts, timers, images — ~116KB gzipped) into
 * the Today bundle. Pointing them at this summary instead keeps the full data
 * on the cook route, where it's actually rendered.
 *
 * Regenerate after editing guided-cook-steps:  pnpm tsx scripts/gen-cook-summary.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  guidedCookData,
  guidedCookMeals,
  type StaticDishData,
} from "../src/data/guided-cook-steps";

function summarize(data: Record<string, StaticDishData>) {
  const out: Record<
    string,
    {
      prepTimeMinutes: number;
      cookTimeMinutes: number;
      ingredientNames: string[];
    }
  > = {};
  for (const [slug, d] of Object.entries(data)) {
    out[slug] = {
      prepTimeMinutes: d.prepTimeMinutes,
      cookTimeMinutes: d.cookTimeMinutes,
      ingredientNames: (d.ingredients ?? []).map((i) => i.name),
    };
  }
  return out;
}

const sideSummary = summarize(guidedCookData);
const mealSummary = summarize(guidedCookMeals);

const body = `// AUTO-GENERATED by scripts/gen-cook-summary.ts — DO NOT EDIT BY HAND.
// Lightweight per-dish summary (times + ingredient names) extracted from the
// ~599KB guided-cook-steps.ts so Today-side clients don't bundle the full cook
// steps. Regenerate: pnpm tsx scripts/gen-cook-summary.ts
/* eslint-disable */

export interface CookSummary {
  prepTimeMinutes: number;
  cookTimeMinutes: number;
  ingredientNames: string[];
}

const SIDE_SUMMARY: Record<string, CookSummary> = ${JSON.stringify(sideSummary)};
const MEAL_SUMMARY: Record<string, CookSummary> = ${JSON.stringify(mealSummary)};

/** Lightweight cook summary for a SIDE slug (times + ingredient names). */
export function getCookSummary(slug: string): CookSummary | null {
  return SIDE_SUMMARY[slug] ?? null;
}
/** Lightweight cook summary for a MEAL slug. */
export function getMealCookSummary(slug: string): CookSummary | null {
  return MEAL_SUMMARY[slug] ?? null;
}
/** Side slugs that have a guided cook. */
export function getAvailableCookSlugs(): string[] {
  return Object.keys(SIDE_SUMMARY);
}
/** Meal slugs that have a guided cook. */
export function getAvailableMealCookSlugs(): string[] {
  return Object.keys(MEAL_SUMMARY);
}
`;

const dest = join(process.cwd(), "src", "data", "guided-cook-summary.ts");
writeFileSync(dest, body);
console.log(
  `Wrote ${dest}: ${Object.keys(sideSummary).length} sides, ${Object.keys(mealSummary).length} meals`,
);
