// Populate guided cook steps for batch 1 of American sides.
// Sources cited inline; recipes adapted from real published versions.
const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '..', 'src', 'data', 'sides.json');
const sides = JSON.parse(fs.readFileSync(file, 'utf8'));

const updates = {
  // Source: J. Kenji Lopez-Alt, Serious Eats — "Creamy Coleslaw"
  // https://www.seriouseats.com/creamy-cole-slaw
  'coleslaw': [
    { step: 1, phase: 'prep', instruction: 'Shred 1 medium head (about 2 lbs) of green cabbage as finely as you can with a sharp knife or mandoline. Grate 2 carrots on the large holes of a box grater at a slight angle so the strands are long. Thinly slice ½ a small red onion.', duration: 8, timerTrigger: false, timerMinutes: null, mistakeWarning: 'Cutting cabbage too thick gives you a chunky, water-logged slaw. Aim for thin ribbons no wider than a pencil lead.', hackChip: 'Grating carrots at a 45° angle along the grater gives you longer, more elegant strands that toss into the cabbage instead of falling to the bottom.', cuisineFact: null },
    { step: 2, phase: 'prep', instruction: 'Toss the cabbage, carrots, and onion in a colander set over a bowl with 2 tsp kosher salt and 2 tsp sugar. Let sit exactly 5 minutes — this purges the water that would otherwise make your slaw soupy.', duration: 5, timerTrigger: true, timerMinutes: 5, mistakeWarning: 'Going past 5 minutes turns the cabbage limp. Set a timer.', hackChip: 'Salt and sugar both pull water out via osmosis. The sugar also pre-seasons the cabbage so it tastes balanced.', cuisineFact: null },
    { step: 3, phase: 'prep', instruction: 'Rinse the cabbage thoroughly under cold water to wash off the salt, then spread it on clean kitchen towels and pat dry. Do not squeeze — squeezing crushes the texture.', duration: 4, timerTrigger: false, timerMinutes: null, mistakeWarning: 'Skipping the rinse leaves the slaw too salty. Skipping the dry leaves it watery the next day.', hackChip: 'A salad spinner works even better than towels for this step.', cuisineFact: null },
    { step: 4, phase: 'cook', instruction: 'In a large bowl, whisk ⅓ cup mayonnaise, 2 Tbsp Dijon mustard, 2 Tbsp apple cider vinegar, 1 Tbsp sugar, ½ tsp celery seed, and a few grinds of black pepper until smooth.', duration: 3, timerTrigger: false, timerMinutes: null, mistakeWarning: null, hackChip: 'Add 1 Tbsp of buttermilk for a tangier, looser dressing — Kenji\'s preferred move.', cuisineFact: null },
    { step: 5, phase: 'finish', instruction: 'Add the dried cabbage mixture to the dressing and toss with tongs until every shred is coated. Taste and adjust with more salt, pepper, or vinegar.', duration: 2, timerTrigger: false, timerMinutes: null, mistakeWarning: null, hackChip: 'Slaw tastes best after 30 minutes in the fridge — flavors meld and the cabbage softens just enough.', cuisineFact: null },
    { step: 6, phase: 'finish', instruction: 'Cover and refrigerate at least 30 minutes before serving. Slaw keeps 3 days covered.', duration: 30, timerTrigger: true, timerMinutes: 30, mistakeWarning: null, hackChip: null, cuisineFact: null }
  ],

  // Source: Serious Eats — "How to Boil Corn on the Cob" (tested method)
  // https://www.seriouseats.com/how-to-boil-corn-on-the-cob
  'corn-on-cob': [
    { step: 1, phase: 'prep', instruction: 'Shuck 4–6 ears of corn — strip back the husk and pull off the silk threads. Snap or cut off the stem. Inspect for any browned kernels and trim them.', duration: 5, timerTrigger: false, timerMinutes: null, mistakeWarning: null, hackChip: 'Run a damp paper towel down the cob from top to bottom — it grabs every last silk strand in one pass.', cuisineFact: null },
    { step: 2, phase: 'cook', instruction: 'Bring a large pot of water to a rolling boil over high heat. Use enough water to fully submerge the corn — about 4 quarts for 4 ears.', duration: 8, timerTrigger: true, timerMinutes: 8, mistakeWarning: 'Salting the boiling water does almost nothing for corn — the cooking time is too short to penetrate. Save the salt for after.', hackChip: null, cuisineFact: null },
    { step: 3, phase: 'cook', instruction: 'Lower the corn into the boiling water, cover the pot, and immediately turn the heat OFF. Let the corn sit, undisturbed, for 10 minutes. The residual heat cooks it perfectly without overdoing it.', duration: 10, timerTrigger: true, timerMinutes: 10, mistakeWarning: 'Boiling corn at full heat for 10 minutes makes it rubbery and starchy. The off-heat method is the Serious Eats-tested winner.', hackChip: 'Frozen corn works too — add 2 extra minutes.', cuisineFact: null },
    { step: 4, phase: 'finish', instruction: 'Lift the corn out with tongs onto a plate. Immediately rub each ear with a pat of softened butter and shower with flaky salt while still steaming hot.', duration: 2, timerTrigger: false, timerMinutes: null, mistakeWarning: null, hackChip: 'Roll the buttered corn in a shallow plate of grated Parmesan and chopped chives for an instant upgrade.', cuisineFact: 'Sweet corn loses about 50% of its sweetness within 24 hours of picking — the fresher the better.' }
  ],

  // Source: J. Kenji Lopez-Alt, Serious Eats — "Perfect Twice-Fried French Fries"
  // https://www.seriouseats.com/perfect-thin-and-crispy-french-fries-recipe
  'french-fries': [
    { step: 1, phase: 'prep', instruction: 'Peel 2 lbs (about 4) russet potatoes. Cut into ¼-inch by ¼-inch sticks — uniform thickness is crucial for even cooking. Drop the sticks into a bowl of cold water as you go to prevent browning.', duration: 12, timerTrigger: false, timerMinutes: null, mistakeWarning: 'Using waxy potatoes (red, Yukon) makes soggy fries. Russets have the right starch content.', hackChip: 'Square off the potato first by cutting a thin slab off each side — this gives you uniform sticks instead of awkward curved pieces.', cuisineFact: null },
    { step: 2, phase: 'prep', instruction: 'Drain the potatoes and place them in a large pot. Cover with cold water by 1 inch, add 2 Tbsp white vinegar and 2 Tbsp kosher salt. Bring to a boil, then reduce to a bare simmer for 10 minutes until the fries are nearly tender but hold their shape.', duration: 12, timerTrigger: true, timerMinutes: 10, mistakeWarning: 'Skipping the vinegar makes fries that turn to mush in the boil. The acid keeps the pectin firm.', hackChip: 'This boiled-then-fried method is Kenji\'s breakthrough — it gelatinizes the surface starches so the fries crisp up instantly when fried.', cuisineFact: null },
    { step: 3, phase: 'prep', instruction: 'Drain the fries gently and spread them on a paper-towel-lined baking sheet. Pat dry. Let them air-dry for 5 minutes — surface moisture is the enemy of crispness.', duration: 5, timerTrigger: true, timerMinutes: 5, mistakeWarning: 'Wet fries make the oil splatter dangerously and create a soggy crust.', hackChip: null, cuisineFact: null },
    { step: 4, phase: 'cook', instruction: 'Heat 2 quarts of peanut or canola oil in a Dutch oven to 400°F (use a thermometer). Working in 3 batches, fry the potatoes for 50 seconds per batch — they should be pale and limp when removed. Let oil return to 400°F between batches.', duration: 8, timerTrigger: true, timerMinutes: 8, mistakeWarning: 'Crowding the oil drops the temperature and gives you greasy fries. Three batches, no shortcuts.', hackChip: 'After this first fry, you can refrigerate the fries for up to a day before the second fry — perfect for entertaining.', cuisineFact: null },
    { step: 5, phase: 'cook', instruction: 'Increase oil temperature to 400°F. Fry the potatoes a second time, all together this time, until deep golden brown and crispy, 3–4 minutes. Stir gently with a spider to prevent sticking.', duration: 4, timerTrigger: true, timerMinutes: 4, mistakeWarning: null, hackChip: null, cuisineFact: null },
    { step: 6, phase: 'finish', instruction: 'Transfer fries to a paper-towel-lined bowl, immediately season with kosher salt while shiny with oil so the salt sticks. Toss to coat. Serve right now — fries lose their crisp within 5 minutes.', duration: 1, timerTrigger: false, timerMinutes: null, mistakeWarning: 'Salting after they cool means the salt slides off. Salt while hot.', hackChip: null, cuisineFact: null }
  ],

  // Source: America's Test Kitchen — "Ultimate Extra-Crunchy Onion Rings"
  // https://www.americastestkitchen.com/recipes/12160
  'onion-rings': [
    { step: 1, phase: 'prep', instruction: 'Slice 2 large yellow onions into ½-inch-thick rounds. Separate into individual rings, discarding the small inner rings (or save them for soup). You should have about 24 large rings.', duration: 8, timerTrigger: false, timerMinutes: null, mistakeWarning: 'Slicing thinner than ½ inch gives you flimsy rings that overcook before the crust browns.', hackChip: 'Use sweet onions like Vidalia for a milder flavor that lets the crust shine.', cuisineFact: null },
    { step: 2, phase: 'prep', instruction: 'Soak the onion rings in 2 cups buttermilk with 1 tsp salt for 30 minutes. The buttermilk tenderizes and adds a subtle tang while the salt seasons the onion itself.', duration: 30, timerTrigger: true, timerMinutes: 30, mistakeWarning: null, hackChip: 'No buttermilk? Stir 2 Tbsp lemon juice into 2 cups whole milk and let it sit 5 minutes.', cuisineFact: null },
    { step: 3, phase: 'prep', instruction: 'In a large bowl, whisk together 2 cups all-purpose flour, ½ cup cornstarch, 1 Tbsp baking powder, 2 tsp salt, 1 tsp paprika, and ½ tsp cayenne. The cornstarch is the secret to extra crunch.', duration: 3, timerTrigger: false, timerMinutes: null, mistakeWarning: null, hackChip: 'ATK\'s test was clear: cornstarch + flour beats flour alone every time. The cornstarch fries up shatter-crisp.', cuisineFact: null },
    { step: 4, phase: 'cook', instruction: 'Heat 2 quarts of vegetable oil in a Dutch oven to exactly 375°F. A thermometer is non-negotiable — too low and the rings absorb oil; too high and they burn before cooking through.', duration: 10, timerTrigger: true, timerMinutes: 10, mistakeWarning: 'Eyeballing oil temperature is the #1 onion ring failure. Get a clip-on thermometer.', hackChip: null, cuisineFact: null },
    { step: 5, phase: 'cook', instruction: 'Working in batches, lift rings from buttermilk, let excess drip off, then dredge in the flour mixture, pressing firmly so the coating sticks. Re-dip in buttermilk and dredge again for a double coat.', duration: 5, timerTrigger: false, timerMinutes: null, mistakeWarning: 'Skipping the double-dredge gives you a thin crust that falls off in the oil.', hackChip: 'ATK shakes all the rings together with the flour mix in a paper grocery bag — faster and more even than dredging one by one.', cuisineFact: null },
    { step: 6, phase: 'cook', instruction: 'Lower 6–8 rings into the oil with tongs. Fry without stirring for 30–60 seconds to set the crust, then stir gently and continue frying until dark golden brown, 3–5 minutes total.', duration: 5, timerTrigger: true, timerMinutes: 5, mistakeWarning: 'Stirring too early knocks off the wet coating before it can set.', hackChip: null, cuisineFact: null },
    { step: 7, phase: 'finish', instruction: 'Transfer to a wire rack set over a baking sheet (not paper towels — they trap steam and soften the crust). Sprinkle with flaky salt immediately. Repeat with remaining rings, returning oil to 375°F between batches.', duration: 2, timerTrigger: false, timerMinutes: null, mistakeWarning: 'Resting hot fried food on paper towels is how you ruin onion rings. Always use a wire rack.', hackChip: null, cuisineFact: null }
  ],

  // Source: The Kitchn / Cookie and Kate — Crispy Baked Sweet Potato Fries (cornstarch method)
  // https://cookieandkate.com/baked-sweet-potato-fries/
  'sweet-potato-fries': [
    { step: 1, phase: 'prep', instruction: 'Preheat the oven to 425°F and line two large baking sheets with parchment paper. Hot oven + two pans (so fries have room) is the foundation of crispy oven fries.', duration: 12, timerTrigger: true, timerMinutes: 12, mistakeWarning: 'Crowding fries onto one pan steams them. Two pans is non-negotiable for crispness.', hackChip: null, cuisineFact: null },
    { step: 2, phase: 'prep', instruction: 'Peel 2 lbs sweet potatoes (about 2 large) and cut into matchsticks ¼-inch thick on each side. Uniform size = uniform crispness.', duration: 10, timerTrigger: false, timerMinutes: null, mistakeWarning: 'Cutting fries thicker than ¼ inch leaves them soft inside while the outside burns.', hackChip: 'Square off the round sides of the potato first — easier to get straight cuts from a flat surface.', cuisineFact: null },
    { step: 3, phase: 'prep', instruction: 'Soak the cut fries in a bowl of cold water for at least 30 minutes (up to 2 hours). This pulls out surface starches that would otherwise turn gummy.', duration: 30, timerTrigger: true, timerMinutes: 30, mistakeWarning: 'Skipping the soak is the #1 reason home-baked sweet potato fries come out limp.', hackChip: null, cuisineFact: null },
    { step: 4, phase: 'prep', instruction: 'Drain the fries and dry them THOROUGHLY with kitchen towels — pat each one until no water remains. Toss in a dry bowl with 2 Tbsp cornstarch until every fry is lightly coated.', duration: 5, timerTrigger: false, timerMinutes: null, mistakeWarning: 'Wet fries + cornstarch = paste. Dry first, cornstarch second.', hackChip: 'The order matters: oil only AFTER the cornstarch coats. Cornstarch on dry fries → then drizzle 2 Tbsp oil → toss to coat.', cuisineFact: null },
    { step: 5, phase: 'prep', instruction: 'Drizzle 2 Tbsp olive oil over the cornstarched fries and toss to coat evenly. Season with 1 tsp salt, ½ tsp garlic powder, and ½ tsp smoked paprika. Spread in a single layer across both baking sheets — fries should not touch.', duration: 4, timerTrigger: false, timerMinutes: null, mistakeWarning: null, hackChip: null, cuisineFact: null },
    { step: 6, phase: 'cook', instruction: 'Bake on the center and lower racks for 20 minutes. Pull both pans, flip every fry with a thin metal spatula, and rotate the pans (top to bottom, front to back).', duration: 20, timerTrigger: true, timerMinutes: 20, mistakeWarning: null, hackChip: 'A thin metal spatula slides under without ripping the cornstarch coating.', cuisineFact: null },
    { step: 7, phase: 'cook', instruction: 'Return to the oven and bake another 10–15 minutes, until the fries are deep golden brown at the edges and crisp. Watch the last 5 minutes carefully — sweet potatoes go from perfect to burnt fast.', duration: 12, timerTrigger: true, timerMinutes: 12, mistakeWarning: 'Sweet potatoes have more sugar than russets and burn quickly. Stay close at the end.', hackChip: null, cuisineFact: null },
    { step: 8, phase: 'finish', instruction: 'Let the fries cool on the pan for 3–5 minutes — they continue to crisp as they cool. Transfer to a serving plate and add a final sprinkle of flaky salt.', duration: 4, timerTrigger: false, timerMinutes: null, mistakeWarning: null, hackChip: 'Serve with chipotle aioli: ½ cup mayo + 1 minced chipotle in adobo + squeeze of lime.', cuisineFact: null }
  ]
};

let updated = 0;
for (const side of sides) {
  if (updates[side.id]) {
    side.guidedCookSteps = updates[side.id];
    updated++;
    console.log('Populated:', side.id);
  }
}

fs.writeFileSync(file, JSON.stringify(sides, null, 2) + '\n');
console.log('Updated', updated, 'sides. Total in file:', sides.length);
